### ISSUE TITLE
MIT or GPL License

### ISSUE THREAD

**Issue by toddrme2178** [rocky/python-xdis#12]
The license listed in the `LICENSE` file is MIT.  However, the license of the code in the `xdis/dropbox` folder is GPL-2.0.  How does that affect the overall license of the xdis package?

**Comment by rocky** [comment]
Well, one can automatically convert MIT to GPL-2.0, but it is harder to go the other way, I'd need the buyoff from the person that wrote that. If this is not the answer you want we'd need to contact the author of decrypt25.py and I'd leave that to you since this is more of a concern to you. 

If you are leaning GPL-2.0ish, I can fix up the other files so that's the case.

**Comment by toddrme2178** [comment]
I am trying create an rpm of the package on openSUSE.  It isn't a big issue
what the license is from my standpoint, I just need to make sure the
license we list is the license that actually applies.  The distribution is
strict about making sure licensing is correct in packages they ship as part
of the core distribution, and this package is a dependency of one such
package.

**Comment by rocky** [comment]
Ok. We can go with GPL-2.0. Would you make a merge request for the appropriate changes? Thanks.
