### ISSUE TITLE
bytecode not working after disasm and xasm

### ISSUE THREAD

**Issue by zzh1996** [rocky/python-xdis#38]
for this pyc file (from a CTF problem):
https://hackme.inndy.tw/static/pyyy.pyc

```
$ pydisasm --asm pyyy.pyc > pyyy_disasm.pyasm

$ pyc-xasm pyyy_disasm.pyasm                
Wrote pyyy_disasm.pyc

$ python pyyy_disasm.pyc       
Traceback (most recent call last):
  File "pyyy.py", line 16, in <module>
  File "pyyy.py", line 25, in <lambda>
TypeError: unsupported operand type(s) for +: 'function' and 'function'
```

**Comment by rocky** [comment]
Congratulations - you are the first person that I am aware of that has tried to use `--asm` and `pyc-xasm`.

The problem is basically that functions can have the same name and <lambda> or <genexpr> are common cases of that.  Internally the python interpreter doesn't use the code name but its hex address.

The xasm project also has a commit relevant to handling this. And it may even turn out that uncompyle6 will need a change too. 

21db33a starts to address this, but I've run out of patience for today. See the FIXME in that commit for what remains in case you want to carry on.  

BTW I use the star ratings of a project to help me determine which of several projects to work on, all other things being equal. This particular project and the xasm project have low rating compared to the others, so this is a lower priority thing.

**Comment by zzh1996** [comment]
When I use uncompyle6 to decompile this pyc file, I got some python codes which run into syntax errors. This is actually why I start to try python-xdis. Since uncompyle6 is the most starred project, you can fix the uncompyle6 bug first.

**Comment by rocky** [comment]
> you can fix the uncompyle6 bug first.

Um. It doesn't work like that. Dependencies are dependencies. It is not clear right now if there is a bug in uncompyle6.

**Comment by zzh1996** [comment]
I am sure that I am using the latest git version.

```
$ uncompyle6 pyyy.pyc > a.py
$ python a.py
  File "a.py", line 21
    l = (lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args))))(lambda f: lambda x:     if x < 2:
                                                                                                      ^
SyntaxError: invalid syntax
```

You can open the decompiled python code. There is something wrong obviously at line 21 and 22

**Comment by rocky** [comment]
Ok. Read [How to Report a Bug](https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md), and follow those instructions filed in uncompyle6's issue tracker.

**Comment by zzh1996** [comment]
thanks. I narrowed the problem and filed an issue https://github.com/rocky/python-uncompyle6/issues/130

**Comment by racterub** [comment]
@zzh1996 This shouldn't be the issue, the uncompyle6's output is correct.
