### ISSUE TITLE
Installed via pip, can't execute pydisasm

### ISSUE THREAD

**Issue by Marrin** [rocky/python-xdis#42]
I'm using the Ubuntu 18.04 supplied Python 3.6.6 and the latest `pip` to install xdis globally:
```
$ python3 --version
Python 3.6.6
$ python3 -m pip --version
pip 18.0 from /home/bj/.local/lib/python3.6/site-packages/pip (python 3.6)
$ pydisasm
bash: /usr/local/bin/pydisasm: /home/rocky/.pyenv/versions/3.6.6/bin/python: bad interpreter: No such file or directory
$ head -1 /usr/local/bin/pydisasm
#!/home/rocky/.pyenv/versions/3.6.6/bin/python
```
That she bang line is already in the wheel file and definately not portable. :-)

**Comment by rocky** [comment]
What was in git in fact did not have a "she bang" that is wrong. Wheel building helpfully changed something that was reasonable into something that was not. I find Python is often too clever by a half, or clumsy by design forcing being too clever by a half. 

Until another release goes out,  I think you can install via tarball which doesn't have the additional cleverness, or as you probably have done, modify the first line.
