### ISSUE TITLE
Support standard dis api

### ISSUE THREAD

**Issue by moagstar** [rocky/python-xdis#6]
I think it would be nice to support the standard dis api:

https://docs.python.org/2/library/dis.html

I think in terms of the principal of least surprise it would be nice to be able to use xdis as a drop in replacement for the dis module, but then with the supercharged power of cross version + the better semantics of python 3 dissasembly (i.e. being able to iterate through Instructions rather than just getting a string)

@rocky What are your thoughts?

**Comment by rocky** [comment]
As a guiding principle it is a great idea.  There are however some kinks and caveats one has to work out when you get into the details. Let's start out with the link you cite. 

It lists `dis.distb([tb])`. This doesn't make sense cross version, just within a given version since a traceback is a "live" object, not a static object that you'd get from compiled code. Duplicating that function inside xdis feels more like overhead than providing value. 

The next thing to work out is what exactly forms the API. Is it what is documented in that link? Because when you look at the underlying code, there are way more functions listed there. 

The next thing you need to decide on is, is: which API? Take a look now at https://docs.python.org/3/library/dis.html and you'll find that classes _Bytecode_ and _Instruction_  have been added. (Hmm - note that the class name is _still_ `Bytecode` even though sometimes it is a word code. 

That is more or less what I've been following. In other words, I've been following the latest API rather than the API that was in effect for the version of the compiled file.  So in particular even for 2.7 running 2.7, you are getting the 3x API to the extent that it has been implemented.

And that then extends, somewhat, to how instructions are printed. 

The last caveat has to do with who is going to do the work. I'll follow these guidelines as (I think) I have been trying to do. It is not something I personally want to spend a lot of time doing given that there are so many other things. Like detecting magic for PyPy version 3. 

However if others want to work on it, that's great.
