### ISSUE TITLE
Add Python 3.11 opcodes and support 3.11

### ISSUE THREAD

**Issue by rocky** [rocky/python-xdis#98]
## Description

Add support for Python 3.11

## Background

Python 3.11 is out!

## Tests

After adding opcode and adjusting: 

```
make check
```

**Comment by Anutrix** [comment]
In order to add support for 3.11, one would need to read and understand https://docs.python.org/3.11/whatsnew/3.11.html#cpython-bytecode-changes and create file called `xdis/opcodes/opcode_311.py` with necessary data, correct?

One more doubt: When using uncompyle6 installed on a system with python 3.11 but de-compiling older pyc(from e.g, 3.10), the KeyError is still says `3.11.x`. Is this expected? Shouldn't it either work or complain about 3.10 KeyError?
Is it because uncompyle6 can't determine the version before de-compilation can be done?

**Comment by rocky** [comment]
> Shouldn't it either work or complain about 3.10 KeyError?
> Is it because uncompyle6 can't determine the version before de-compilation can be done?

If you'd like to work up a solution here for uncompyle6, please do.

**Comment by Sirin112** [comment]
I lost my code accidently, and really need xdis support for Python 3.11, I can pay for it ! plzzzzzzzzzzzzzzz !

**Comment by rocky** [comment]
@Sirin112 There is preliminary support for 3.11 in the master branch. If that does not do it for you. Make a reasonable donation to the project and send me the bytecode and I will send back a disassembly of your bytecode.

**Comment by Sirin112** [comment]
> 

it shows that Unknown magic number 227，how much could be a reasonable donation? will $150 be enough?

**Comment by rocky** [comment]
> it shows that Unknown magic number 227，how much could be a reasonable donation? will $150 be enough?

Something is weird then. If you donate $150 I will spend about 1/2 hour on it. After making the donation you can send the byteocode to python.decompiler39plus@gmail.com

**Comment by martindemello** [comment]
[pycnite](https://github.com/google/pycnite) has 3.11 support. you likely won't be able to import and use it in xdis because it requires python >= 3.8 to run but you're welcome to copy code from it.

**Comment by rocky** [comment]
So everyone know where things stand...

@2elli added 3.11 of opcode support in  #112 #113 among others and I added better unmarshaling #119 .  

Python version _independent_ line number table disassembly (or better since 3.11 can do better) still needs doing, although if you disassemble 3.11 pyc from 3.11 that works.

**Comment by rocky** [comment]
Thanks to @2elli @caandt and @jdw170000 , I think we can call this done.
